src/AppBundle/Entity/Application.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;

class Application
{
    private $id;
    private $student;
    private $promotion;
    private $statusModifications;
    private $currentState = "";
    private $dataAttachments;

    public function __construct()
    {
        $this->dataAttachments = new ArrayCollection();
    }

    public function getId() : int
    {
        return $this->id;
    }

    public function getStudent()
    {
        return $this->student;
    }

    public function setStudent($student)
    {
        $this->student = $student;
    }

    public function getPromotion(): Promotion
    {
        return $this->promotion;
    }

    public function setPromotion($promotion)
    {
        $this->promotion = $promotion;
    }

    public function getStatusModifications()
    {
        return $this->statusModifications;
    }

    public function setStatusModification(State $statusModifications)
    {
        $this->statusModifications = $statusModifications;
    }

    public function addStatusModification(StatusModification $statusModifications)
    {
        $this->statusModifications[] = $statusModifications;
        $statusModifications->setApplication($this);

        return $this;
    }

    public function removeStatusModification(StatusModification $statusModifications)
    {
        $this->statusModifications->removeElement($statusModifications);
    }

    public function getLastStatusModification(){
        return $this->statusModifications->first();
    }

    public function getCurrentState()
    {
        return $this->currentState;
    }

    public function setCurrentState($currentState)
    {
        $this->currentState = $currentState;
    }

    public function getDataAttachments()
    {
        return $this->dataAttachments;
    }

    public function setDataAttachments($dataAttachments)
    {
        $this->dataAttachments = $dataAttachments;
    }

    public function addDataAttachments(DataAttachments $dataAttachment)
    {
        $insert = true;
        foreach ($this->dataAttachments as $stockedDataAttachment){
            if($dataAttachment instanceof $stockedDataAttachment){
                $insert = false;
            }
        }

        if($insert){
            $this->dataAttachments[] = $dataAttachment;
            $dataAttachment->setApplication($this);
        }

        return $this;
    }

    public function removeDataAttachments(DataAttachments $dataAttachments)
    {
        $this->dataAttachments->removeElement($dataAttachments);
    }
}

src/AppBundle/Entity/User/Jury.php
<?php

namespace AppBundle\Entity\User;

use AppBundle\Entity\Course;
use AppBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;

class Jury extends User
{
    protected $id;
    private $phoneNumber;
    private $coursesAttached;

    public function __construct()
    {
        parent::__construct();
        $this->coursesAttached = new ArrayCollection();
    }


    public function getId() : int
    {
        return $this->id;
    }

    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber($phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;
    }

    public function getCoursesAttached()
    {
        return $this->coursesAttached;
    }

    public function setCoursesAttached($coursesAttached)
    {
        $this->coursesAttached = $coursesAttached;
    }

    public function addCoursesAttached(Course $course)
    {
        $this->coursesAttached[] = $course;

        return $this;
    }

}

src/AppBundle/Controller/JuryController.php
<?php
/**
 * Created by PhpStorm.
 * User: lp
 * Date: 05/05/2017
 * Time: 16:03
 */

namespace AppBundle\Controller;


use AppBundle\Entity\Application;
use AppBundle\Entity\Course;
use AppBundle\Entity\Promotion;
use AppBundle\Entity\State;
use AppBundle\Forms\Types\Applications\ChangeStatusType;
use AppBundle\Forms\Types\PromotionFormType;
use AppBundle\Forms\Types\SearchStudentType;
use AppBundle\Forms\Types\StudentsCsvType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

class JuryController extends Controller
{
    public function juryIndexAction(Request $request)
    {

        $jury = $this->getUser();

        if (count($jury->getCoursesAttached()->toArray()))
            $courseAttached = $jury->getCoursesAttached()->toArray();

        if (count($jury->getCoursesAttached()->toArray())) {
            return $this->render('AppBundle:Jury:home.html.twig', [
                'courseAttached' => $courseAttached
            ]);
        } else {
            return $this->render('AppBundle:Jury:home.html.twig');
        }
    }

    /**
     * @ParamConverter("promotion", options={"mapping": {"promotionId" : "id"}})
     */
    public function studentListAction(Request $request, Promotion $promotion)
    {
        $em = $this->getDoctrine()->getManager();

        $applications = $em->getRepository(Application::class)->findAllWhereJuryCanEdit($promotion);

        $states = $em->getRepository(State::class)->findBy(
            ['workflow' => $promotion->getWorkflow()]
        );

        $promotionsForm = $this->createForm(PromotionFormType::class, null, [
            "promotions" => $promotion->getCourse()->getPromotions(),
            "promotionSelected" => $promotion
        ]);
        $searchForm = $this->createForm(SearchStudentType::class, null, ['states' => $states]);

        if ($request->isMethod('post')) {
            $promotionsForm->handleRequest($request);
            $searchForm->handleRequest($request);

            if ($promotionsForm->isSubmitted() && $promotionsForm->isValid()) {
                return $this->redirectToRoute('jury.promotion', ['promotionId' => $promotionsForm->getData()['promotions']->getId()]);
            }

            if ($searchForm->isSubmitted() && $searchForm->isValid()) {
                $applications = $em->getRepository(Application::class)->findByPromotionAndFiltersWhereJuryCanEdit($promotion, $searchForm->getData());
            }
        }

        return $this->render('@App/Jury/studentList.html.twig', [
            'course' => $promotion->getCourse(),
            'promotion' => $promotion,
            'applications' => $applications,
            'promotionsForm' => $promotionsForm->createView(),
            'searchForm' => $searchForm->createView()
        ]);
    }


    /**
     * @ParamConverter("application", options={"mapping": {"applicationId" : "id"}})
     */
    public function viewApplicationAction(Request $request, Application $application)
    {
        $workflow = $this->get('app.factory.workflow')->generateWorflowFromApplication($application);
        $transitions = $workflow->getEnabledTransitions($application);

        $realTransitions = $application->getPromotion()->getWorkflow()->getTransitions()->toArray();

        $result = [];
        foreach ($realTransitions as $realTransition) {
            foreach ($transitions as $workflowTransition) {
                if ($realTransition->getMachineName() == $workflowTransition->getName()) {
                    $result[] = $realTransition;
                }
            }
        }

        $form = $this->createForm(ChangeStatusType::class, null, array('transitions' => $result));

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $application = $this->get('app.application')->setState($application, $data);

            return $this->redirectToRoute('jury.promotion', ['promotionId' => $application->getPromotion()->getId()]);
        }
        return $this->render('AppBundle:Jury:viewApplication.html.twig', [
            'form' => $form->createView(),
            'application' => $application,
            'promotionId' => $application->getPromotion()->getId()
        ]);
    }
}

src/AppBundle/Resources/views/Jury/home.html.twig
{% extends '::base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}Accueil formateur{% endblock %}

{% block body %}
    <h1>Formations</h1>
    <hr>
    {% if courseAttached is defined %}
        {% for course in courseAttached %}
            {% include "AppBundle:Course:showJury.html.twig" with {"courseId": course.id} %}
        {% endfor %}
    {% else %}
        <div class="alert alert-info" role="alert">
            Pas de formations attribuées.
        </div>
    {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Jury/personalInformations.html.twig
{% extends '::base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link href="{{ ('/suivi_alternants/web/css/form.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}Informations personnelles{% endblock %}

{% block body %}
    <h1>Mes informations personnelles</h1>
    <a href="{{ path('changePassword') }}" class="btn btn-primary">Changer le mot de passe</a>

    <div id="courseManagerInformation">
        {{ form_start(jury) }}
        {{ form_widget(jury) }}
        <input type="submit" class="btn btn-primary">
        {{ form_end(jury) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Jury/studentList.html.twig
{% extends '::base.html.twig' %}

{% block title %}Liste des étudiant - {{ course.name }}{% endblock %}

{% block body %}

    <h1 class="d-inline">{{ course.name }}</h1>
    <hr>

    {% if promotion %}
        <div class="row col-12 mb-4">
            {{ form_start(promotionsForm, {
                'attr': { 'class': 'form-inline' }
            }) }}
            <div class="form-group">
                <h4>{{ form_label(promotionsForm.promotions, null, { 'label_attr': { 'class': 'mr-sm-2' } }) }}</h4>
                {{ form_widget(promotionsForm.promotions, { 'attr': {
                    'class': 'form-control mb-2 mr-sm-2 mb-sm-0',
                    'onchange': 'this.form.submit();' }
                }) }}
                <span><span class="badge badge-default ml-2 mr-1">{{ promotion.studentNumber }}</span>places maximum</span>
            </div>
            {{ form_rest(promotionsForm) }}
            {{ form_end(promotionsForm) }}
        </div>

        {% if promotion.workflow %}
            <h4>Liste des étudiants</h4>
            <hr>

            {{ form_start(searchForm, { 'attr': { 'class': 'form-inline mb-4' } }) }}
            {{ form_widget(searchForm.lastName, { 'attr': { 'class': 'form-control mb-2 mr-sm-2 mb-sm-0' } }) }}
            {{ form_widget(searchForm.firstName, { 'attr': { 'class': 'form-control mb-2 mr-sm-2 mb-sm-0' } }) }}
            {{ form_widget(searchForm.currentState, { 'attr': { 'class': 'form-control mb-2 mr-sm-2 mb-sm-0' } }) }}
            <button type="submit" class="btn btn-secondary form-control mb-2 mr-sm-2 mb-sm-0" role="button">
                Rechercher <i class="fa fa-search" aria-hidden="true"></i>
            </button>
            <button class="btn btn-secondary"
                    onclick="for (var elem in this.form.elements) { this.form.elements[elem].value = ''; } this.form.submit();">
                <i class="fa fa-refresh" aria-hidden="true"></i>
            </button>
            {{ form_end(searchForm) }}

            {% if applications %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Statut</th>
                    </thead>
                    <tbody>
                    {% for application in applications %}
                        <tr>
                            <th>{{ loop.index }}</th>
                            <td>{{ application.student.lastName }}</td>
                            <td>{{ application.student.firstName }}</td>
                            <td>
                                {% if application.getLastStatusModification() %}
                                    <a href="{{ path('jury.application.view', {'applicationId': application.id }) }}">
                                        {{ application.getLastStatusModification().state.name }}
                                    </a>
                                {% else %}
                                    <a href="{{ path('jury.application.view', {'applicationId': application.id }) }}">
                                        Application with no status
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="alert alert-info" role="alert">
                    Aucun dossier où vous avez les droits d'intervenir.
                </div>
            {% endif %}

        {% else %}
            <div class="alert alert-info" role="alert">
                Pas d'étudiants pour cette promotion.
            </div>
        {% endif %}
    {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Jury/viewApplication.html.twig
{% extends '::base.html.twig' %}

{% block title %}Détails d'une candidature{% endblock %}

{% block body %}
    <h1>{{ application.student.firstName }} {{ application.student.lastName }}</h1>
    <hr>

    <h2 class="mb-4">Statut : {{ application.lastStatusModification.state.name }}</h2>

    <div class="workflow-dump text-center p-4 mb-4 bordered zoom-in" style="display: none">
        {{ app_factory_workflow.customDumpWorflowFromApplication(application) }}
    </div>

    <div class="mb-4">
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.transition) }}
            {{ form_widget(form.transition) }}
        </div>
        <div class="form-group">
            {{ form_label(form.comment) }}
            {{ form_widget(form.comment, { 'attr': { 'rows': '5' } }) }}
            {{ form_errors(form.comment) }}
        </div>
        <a href="{{ path('jury.promotion', { 'promotionId': promotionId }) }}"
           class="btn btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> Retour</a>
        <input type="submit" class="btn btn-primary"/>
        {{ form_end(form) }}
    </div>

    <div>
        <h4>Historique des étapes</h4>
        <table class="table">
            <thead>
            <tr>
                <th>Status</th>
                <th>Date de modification</th>
                <th>Commentaire</th>
            </tr>
            </thead>
            <tbody>
            {% for statusModification in application.statusModifications %}
                <tr>
                    <td>{{ statusModification.state.name }}</td>
                    <td>{{ statusModification.dateTime | date }}</td>
                    <td>{{ statusModification.comment }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/viz.js') }}"></script>
    <script src="{{ asset('js/workflowDisplay.js') }}"></script>
{% endblock %}